repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
        exclude_types: [markdown]
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/bin/black
        language: python
        types: [python]

      - id: isort
        name: isort
        entry: .venv/bin/isort
        language: python
        types: [python]
        args: []

      - id: flake8
        name: flake8
        entry: .venv/bin/flake8
        language: python
        types: [python]

      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: python
        types: [python]
