version: "3.4"
services:
  postgres:
    image: postgres:12
    hostname: postgres
    ports: 
      - 44444:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farforbot
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
    postgres:
