version: "3.3"
services:
  database:
    image: postgres:12
    hostname: postgres
    ports: 
      - "44444:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farforbot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
