replicaCount: 1
environment: staging

cloudflareSecretName: cloudflare-api-token-secret

image:
  repository: cr.yandex/crptfenqilkr374m9c4i/farfor_bot
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8000

ingress:
  host: bot.khakov.com
  paths:
    - path: /api
      pathType: ImplementationSpecific
    - path: /docs
      pathType: ImplementationSpecific

issuer:
  name: farfor-bot-dns-issuer

certificate:
  commonName: "*.bot.khakov.com"
  issuerName: letsencrypt-dns-issuer
  secretName: wildcard-farfor-bot-tls
  dnsNames:
    - bot.khakov.com
    - "*.bot.khakov.com"

resources:
  requests:
    memory: "256Mi"
    cpu: "300m"
  limits:
    memory: "1024Mi"
    cpu: "900m"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
