apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 8000
          envFrom:
            - secretRef:
                name: app-secret
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            failureThreshold: 1
            periodSeconds: 10
#          livenessProbe:
#            httpGet:
#              path: /api/health/ping
#              port: http
#              httpHeaders:
#                - name: Accept
#                  value: application/json
#            initialDelaySeconds: 120
#            failureThreshold: 1
#            periodSeconds: 10
