secret_key: ENC[AES256_GCM,data:da87DR20edXQa3oJlgW3FR/mxIPpZXpZYjQHpwGr0E9OuGEZJMfYUC9AnZBysR3Vz3Y=,iv:cmOVTlE3OeEXkCZuUgawqG4qpVeysN0SCJpf5iOk5ZA=,tag:MACREkSnFA9p8tXYS3ToaA==,type:str]
telegram_token: ENC[AES256_GCM,data:fYsYf3GNYEkQLI9P238GFw1K6AhrPaJxTs4kiXBAzG6OBrCvEgfWY9z/bx+eRA==,iv:o9Lkyj0yKsZGk5F1X1Qz9SxwoTJxazkgAWtZHHGNr5M=,tag:Y2aHVHU4rbDdBAzVqmP+LQ==,type:str]
database_host: ENC[AES256_GCM,data:9gtQv9T/VzGz1zTULzhH4Ub1lo0nihDqSMQhU/9zdajuercucQ==,iv:BhNMPm1Bx0O2Qvm04/dVAXa8FxGVN2Ak4G1ZMYNn3zc=,tag:9BjEfs740RlIFMNRckOBwA==,type:str]
database_port: ENC[AES256_GCM,data:Agh8QA==,iv:eI9068RTlQec0Led7LQpJEMghUKO1Mu5DUew1sUnYBI=,tag:tO9pi4FcbJmDzRDNKjU+Yw==,type:int]
database_user: ENC[AES256_GCM,data:9k8bsESzp1rCUVVy9M8h4A==,iv:O1gIrq0rFWU8UzLVSaMicMaBBLcKUe+eIQSbnvQ4HyE=,tag:Bi4HRpM2kdp+Nes16pAMWg==,type:str]
database_password: ENC[AES256_GCM,data:SqXyj/9EqQPsVQ==,iv:r+rDoGiY1yJ4+GhoX9DmbgrvL20vKTxbSO+tOdf3vRA=,tag:szRuVKPMI52SRmDwi7dTLA==,type:str]
database_name: ENC[AES256_GCM,data:QBB2emMOwmfy,iv:R5tVWCf0MC7bc58u7fMMDfgZ6cvJWuNIJzLYhyeaG5c=,tag:YBxvZhyVpLKMXDt9Ib2Mqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2021-06-03T21:00:50Z'
    mac: ENC[AES256_GCM,data:KSC7c44MaLKp0TcFx/Upnaitt2EGc8T5EaQmWzVnbEwZOx/LEBjUhRdm7BPnxCmwu1vkKZVSzje7s7i5q5fDh69/7LK1Qszf+mSDVm9uVQd4hGrbGrLf8lu3BGvE3YMrfaGKPyBMoiwrWZgobUnhVjEj3Wa5R7dBTqTC7nZjlj0=,iv:RSN17cO6ZT0n/6XE7A1V5xoPbXUKxDAVso3/Hj8fKxo=,tag:4p2j2/SLbzTLuHnys08jcQ==,type:str]
    pgp:
    -   created_at: '2021-06-03T20:55:50Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA1Vc+DIhTEYYAQv/ZTuVRF3QrFzERmUwJTua8ndLF+8pJinAjOyVYXvLSQKU
            Z84kbw7F8gVgGOnt+c36zN7c0VGhmpy+j0dhorYXlv4YmdM2rVra9kaxeYK/WZ2Z
            wZYbuNOZc+dDBGCsqTuymfMWT9xFdLDN9DbyYmj+RxpcInbi20qWPhsMP59fS+tE
            BHTsMaMDxoVUdH0eQY+mTnZwKKUHXjjxYQVL3ATJMb6PjCQsxrO9Vzjp012RTDW4
            9oWImtxs5ee6rwNKq2xo/Nzv+UezAxpFoj83o32F1zim0zEXwEpz4xaevdn44YeC
            4OyPge5q3YEg3C3nqNnOWzHYj5NyLijNKGvBVGSzkfu8SrNkCtrzRgr5GNQtK4jG
            /fj2bx5EEeO7XqJ8TJrHfc76JLP+cQyYz355fwOppQj1kwr5JJKZUY3XY3oxWw02
            e675/Sv99mx2DbXmKV8145hA/6hX9kYzKxQXtEr/5Nw+pauBc5ZKdCnK9WqBQ+1N
            gNSNggrikdMwKtf1l+eZ0lwBbpTk/EIO2RY0Bck2DjEWDr2eOX0/K09/8t9GlcYG
            0ZY5zWwog8E6rvlQXBZN77RRmkezRbRD8HVognA/Jj8hA+SMF0Eh8JDa5/DcE4CW
            O6UtPTO0FEQebGnCsg==
            =K7zv
            -----END PGP MESSAGE-----
        fp: 773AFC4F448C79D541BD72627CADC021916CE623
    unencrypted_suffix: _unencrypted
    version: 3.0.3
