replicaCount: 1

image:
  repository: rkhakov/farfor_bot
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  host: bot.farfor.pw

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
