"""telegram_user_table

Revision ID: 1621948090
Revises: 1621936118
Create Date: 2021-05-25 18:08:11.055380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1621948090'
down_revision = '1621936118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('staff_city_id', sa.SmallInteger(), nullable=False),
    sa.Column('staff_point_id', sa.SmallInteger(), nullable=False),
    sa.Column('staff_module', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__telegram_user')),
    sa.UniqueConstraint('user_id', name=op.f('uq__telegram_user__user_id'))
    )
    op.create_index(op.f('ix__telegram_user__id'), 'telegram_user', ['id'], unique=False)
    op.create_index(op.f('ix__telegram_user__staff_city_id'), 'telegram_user', ['staff_city_id'], unique=False)
    op.create_index(op.f('ix__telegram_user__staff_point_id'), 'telegram_user', ['staff_point_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__telegram_user__staff_point_id'), table_name='telegram_user')
    op.drop_index(op.f('ix__telegram_user__staff_city_id'), table_name='telegram_user')
    op.drop_index(op.f('ix__telegram_user__id'), table_name='telegram_user')
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
