"""staff_table

Revision ID: 1622069758
Revises: 1621936118
Create Date: 2021-05-27 03:55:58.678709

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1622069758"
down_revision = "1621936118"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "staff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("erp_username", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk__staff")),
        sa.UniqueConstraint("chat_id", name=op.f("uq__staff__chat_id")),
    )
    op.create_index(
        op.f("ix__staff__erp_username"), "staff", ["erp_username"], unique=False
    )
    op.create_index(op.f("ix__staff__id"), "staff", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix__staff__id"), table_name="staff")
    op.drop_index(op.f("ix__staff__erp_username"), table_name="staff")
    op.drop_table("staff")
    # ### end Alembic commands ###
