apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-issuer-secret
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: "{{ .Values.cloudflareApiToken }}"

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.issuerEmail }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ include "chart.fullname" . }}-issuer-secret
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.issuerEmail }}
          apiTokenSecretRef:
            name: {{ include "chart.fullname" . }}-issuer-secret
            key: api-token
