apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
stringData:
  SECRET_KEY: "{{ .Values.secretKey }}"
  TELEGRAM_TOKEN: "{{ .Values.telegramToken }}"
  DATABASE_HOST: "{{ .Values.databaseHost }}"
  DATABASE_PORT: "{{ .Values.databasePort }}"
  DATABASE_USER: "{{ .Values.databaseUser }}"
  DATABASE_PASSWORD: "{{ .Values.databasePassword }}"
  DATABASE_NAME: "{{ .Values.databaseName }}"
